<Project>
    <PropertyGroup>
        <LangVersion>14.0</LangVersion>
        <NoWarn>$(NoWarn);CS1701;CS1702</NoWarn>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <NuGetAuditMode>all</NuGetAuditMode>
        <NuGetAuditLevel>high</NuGetAuditLevel>
    </PropertyGroup>
</Project>
