<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Title>XmlTvSharp</Title>
        <Authors>Mohamed Eddami</Authors>
        <Copyright>Copyright © Mohamed Eddami</Copyright>
        <PackageProjectUrl>https://github.com/eddami/XmlTvSharp</PackageProjectUrl>
        <RepositoryUrl>https://github.com/eddami/XmlTvSharp</RepositoryUrl>
        <PackageTags>xmltv;epg;tv;guide;xml;iptv;jellyfin;parser;writer</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Description>A high-performance XMLTV reader and writer for .NET.</Description>
        <MinVerTagPrefix>v</MinVerTagPrefix>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <EnablePackageValidation>true</EnablePackageValidation>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MinVer" Version="8.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <None Include="../../README.md" Pack="true" PackagePath="/"/>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
        <PackageReference Include="System.Memory" Version="4.6.3"/>
    </ItemGroup>

</Project>
